pre-messages:
  preMessageMap:
    start: "Привет. Пока что меню в разработке, так что не все функции работают"
    menu: "Основное меню"
    cafe: "Это будущий список кафе, который можно листать"
    rent: "Это будущий список аренды, который можно листать"
    entertainment: "Это будущий список развлечений, который можно листать"
    delivery: "Это будущий список доставки, который можно листать"
    taxi: "Это будущий список служб такси, который можно листать"
    error: "Ой! Что то пошло не так... Обратитесь к администратору"
