bot:
  config:
    sleep-time-for-send: 500
    sleep-time-for-receive: 500
  telegram:
    token: "1858534217:AAGk_4zGC92qgpzW_y3FTNT2W6f2rh4cBVA"
    name: "yalta_city_bot"

spring:
  profiles:
    include: menu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yalta
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect